/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import { HTMLStencilElement, JSXBase } from './stencil.core';


export namespace Components {
  interface GecParticle {
    'btnText': string;
    'btnTextOnsubmit': string;
    'colorValidation': string;
    'label': string;
    'loc': string;
    'pid': string;
    'placeholder': string;
    'subText': string;
    'submitFailedMsg': string;
    'submitSuccessMsg': string;
  }
}

declare global {


  interface HTMLGecParticleElement extends Components.GecParticle, HTMLStencilElement {}
  var HTMLGecParticleElement: {
    prototype: HTMLGecParticleElement;
    new (): HTMLGecParticleElement;
  };
  interface HTMLElementTagNameMap {
    'gec-particle': HTMLGecParticleElement;
  }
}

declare namespace LocalJSX {
  interface GecParticle {
    'btnText'?: string;
    'btnTextOnsubmit'?: string;
    'colorValidation'?: string;
    'label'?: string;
    'loc'?: string;
    'pid'?: string;
    'placeholder'?: string;
    'subText'?: string;
    'submitFailedMsg'?: string;
    'submitSuccessMsg'?: string;
  }

  interface IntrinsicElements {
    'gec-particle': GecParticle;
  }
}

export { LocalJSX as JSX };


declare module "@stencil/core" {
  export namespace JSX {
    interface IntrinsicElements {
      'gec-particle': LocalJSX.GecParticle & JSXBase.HTMLAttributes<HTMLGecParticleElement>;
    }
  }
}


